// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  cardDivider: string;
  contain: string;
  contentCard: string;
  end: string;
  headCardItem: string;
  itemCard: string;
  rightCard: string;
  tab: string;
  tabHead: string;
  titleCard: string;
}
declare var cssExports: CssExports;
export = cssExports;
