// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  contain: string;
  tab: string;
  tabHead: string;
}
declare var cssExports: CssExports;
export = cssExports;
